### PR TITLE
bump version.h as well

### PR DESCRIPTION
**Pull request by timkuijsten**

### CODE REVIEW

**Comment by timkuijsten** [comment]
Hi Danny,

while updating the openbsd port of cnagios[1] I encountered this little detail.

[1] http://marc.info/?l=openbsd-ports&m=148028895323490&w=2

**Comment by dannywarren** [comment]
Ah, good catch, thanks!  I'll make sure this gets bumped appropriately from now on.

In regards to the other comment about how it would be nice if cnagios worked with other compatible monitoring platforms - I agree!  Once I get some time away from work, I'm going to wrap up going through the cnagios codebase and decoupling it from requiring a live version of nagios.  Ideally, it should be an open ended tool that can display whatever nagios-like status.dat files you an throw at it.

**Comment by timkuijsten** [comment]
>  Ideally, it should be an open ended tool that can display whatever nagios-like status.dat files you an throw at it.

completely agree! :)

**Comment by dannywarren** [comment]
FYI, here is the github bug for it:
https://github.com/dannywarren/cnagios/issues/6

And here is the FreeBSD PR discussion that spawned it:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212102

**Pull request merged**
